name: Java CI/CD with Gradle

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repo (git pull)
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    #- name: Setup Gradle
    #  uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: chmod +x ./gradlew; ./gradlew build #deux commandes sur la même ligne

    - name: Publish to server
      uses: appleboy/scp-action@master
      with:
        host: 188.245.157.16
        username: root
        password: totonono
        source: "build/libs/demo-0.0.1-SNAPSHOT.jar"
        target: /home/regis/
